kind: pipeline
name: gitbook-docs

steps:
- name: publish
  image: plugins/docker:latest
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: buglan/gitbook-docs
    tags: latest

- name: deploy
  image: appleboy/drone-ssh
  pull: true
  settings:
    host: buglan.org
    port: 28379
    user: root
    key:
      from_secret: deploy_key
    script:
    - docker pull buglan/gitbook-docs:latest
    - docker rm -f docs
    - echo "almost done"
    - docker run --name=docs -p 4000:80 -d buglan/gitbook-docs
    - echo 'success'
